port = 8000

[database.mysql]
max_connections = 5
url = "mysql://root:admin@mysql:3306/premier"

[auth.keycloak]
admin_password = "admin"
admin_username = "keycloak"
realm = "master"
url = "0.0.0.0:8080"

[auth.keycloak.certificate]
algorithm = "$ENV_KEYCLOAK_CERTIFICATE_ALGORITHM"
exponent = "$ENV_KEYCLOAK_CERTIFICATE_EXPONENT"
modulus = "$ENV_KEYCLOAK_CERTIFICATE_MODULUS"
